#[derive(Copy, Clone)]
#[repr(C)]
pub struct TableEntry {
    pub iCode: ::core::ffi::c_ushort,
    pub flags: ::core::ffi::c_uchar,
    pub nRange: ::core::ffi::c_uchar,
}

#[cfg_attr(feature = "test", unsafe(no_mangle))]
pub unsafe extern "C" fn sqlite3FtsUnicodeIsalnum(mut c: ::core::ffi::c_int) -> ::core::ffi::c_int {
    static mut aEntry: [::core::ffi::c_uint; 406] = [
        0x30 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0xe807 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x16c06 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x1ec2f as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2ac07 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2d001 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2d803 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2ec01 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2fc01 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x35c01 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x3dc01 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0xb0804 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0xb480e as ::core::ffi::c_int as ::core::ffi::c_uint,
        0xb9407 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0xbb401 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0xbbc81 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0xdd401 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0xdf801 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0xe1002 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0xe1c01 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0xfd801 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x120808 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x156806 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x162402 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x163c01 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x164437 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x17cc02 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x180005 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x181816 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x187802 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x192c15 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x19a804 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x19c001 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x1b5001 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x1b580f as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x1b9c07 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x1bf402 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x1c000e as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x1c3c01 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x1c4401 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x1cc01b as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x1e980b as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x1fac09 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x1fd804 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x205804 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x206c09 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x209403 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x20a405 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x20c00f as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x216403 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x217801 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x23901b as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x240004 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x24e803 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x24f812 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x254407 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x258804 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x25c001 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x260403 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x26f001 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x26f807 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x271c02 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x272c03 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x275c01 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x278802 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x27c802 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x27e802 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x280403 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x28f001 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x28f805 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x291c02 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x292c03 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x294401 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x29c002 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x29d401 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2a0403 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2af001 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2af808 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2b1c03 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2b2c03 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2b8802 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2bc002 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2c0403 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2cf001 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2cf807 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2d1c02 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2d2c03 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2d5802 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2d8802 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2dc001 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2e0801 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2ef805 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2f1803 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2f2804 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2f5c01 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2fcc08 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x300403 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x30f807 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x311803 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x312804 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x315402 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x318802 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x31fc01 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x320802 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x32f001 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x32f807 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x331803 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x332804 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x335402 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x338802 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x340802 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x34f807 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x351803 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x352804 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x355c01 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x358802 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x35e401 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x360802 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x372801 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x373c06 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x375801 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x376008 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x37c803 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x38c401 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x38d007 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x38fc01 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x391c09 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x396802 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x3ac401 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x3ad006 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x3aec02 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x3b2006 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x3c041f as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x3cd00c as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x3dc417 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x3e340b as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x3e6424 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x3ef80f as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x3f380d as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x40ac14 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x412806 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x415804 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x417803 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x418803 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x419c07 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x41c404 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x42080c as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x423c01 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x426806 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x43ec01 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x4d740c as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x4e400a as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x500001 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x59b402 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x5a0001 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x5a6c02 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x5bac03 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x5c4803 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x5cc805 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x5d4802 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x5dc802 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x5ed023 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x5f6004 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x5f7401 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x60000f as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x62a401 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x64800c as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x64c00c as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x650001 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x651002 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x66c011 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x672002 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x677822 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x685c05 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x687802 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x69540a as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x69801d as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x69fc01 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x6a8007 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x6aa006 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x6c0005 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x6cd011 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x6d6823 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x6e0003 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x6e840d as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x6f980e as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x6ff004 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x709014 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x70ec05 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x71f802 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x730008 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x734019 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x73b401 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x73c803 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x770027 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x77f004 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x7ef401 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x7efc03 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x7f3403 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x7f7403 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x7fb403 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x7ff402 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x800065 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x81a806 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x81e805 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x822805 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x82801a as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x834021 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x840002 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x840c04 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x842002 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x845001 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x845803 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x847806 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x849401 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x849c01 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x84a401 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x84b801 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x84e802 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x850005 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x852804 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x853c01 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x864264 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x900027 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x91000b as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x92704e as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x940200 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x9c0475 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x9e53b9 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0xad400a as ::core::ffi::c_int as ::core::ffi::c_uint,
        0xb39406 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0xb3bc03 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0xb3e404 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0xb3f802 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0xb5c001 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0xb5fc01 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0xb7804f as ::core::ffi::c_int as ::core::ffi::c_uint,
        0xb8c00c as ::core::ffi::c_int as ::core::ffi::c_uint,
        0xba001a as ::core::ffi::c_int as ::core::ffi::c_uint,
        0xba6c59 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0xbc00d6 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0xbfc00c as ::core::ffi::c_int as ::core::ffi::c_uint,
        0xc00005 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0xc02019 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0xc0a807 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0xc0d802 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0xc0f403 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0xc26404 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0xc28001 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0xc3ec01 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0xc64002 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0xc6580a as ::core::ffi::c_int as ::core::ffi::c_uint,
        0xc70024 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0xc8001f as ::core::ffi::c_int as ::core::ffi::c_uint,
        0xc8a81e as ::core::ffi::c_int as ::core::ffi::c_uint,
        0xc94001 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0xc98020 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0xca2827 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0xcb003f as ::core::ffi::c_int as ::core::ffi::c_uint,
        0xcc0100 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x1370040 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2924037 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x293f802 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2983403 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x299bc10 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x29a7c01 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x29bc008 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x29c0017 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x29c8002 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x29e2402 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2a00801 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2a01801 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2a02c01 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2a08c09 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2a0d804 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2a1d004 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2a20002 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2a2d011 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2a33802 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2a38012 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2a3e003 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2a4980a as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2a51c0d as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2a57c01 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2a60004 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2a6cc1b as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2a77802 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2a8a40e as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2a90c01 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2a93002 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2a97004 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2a9dc03 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2a9ec01 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2aac001 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2aac803 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2aadc02 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2aaf802 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2ab0401 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2ab7802 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2abac07 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2abd402 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x2af8c0b as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x3600001 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x36dfc02 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x36ffc02 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x37ffc01 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x3ec7801 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x3eca401 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x3eec810 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x3f4f802 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x3f7f002 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x3f8001a as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x3f88007 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x3f8c023 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x3f95013 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x3f9a004 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x3fbfc01 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x3fc040f as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x3fc6807 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x3fcec06 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x3fd6c0b as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x3ff8007 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x3ffa007 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x3ffe405 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x4040003 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x404dc09 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x405e411 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x406400c as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x407402e as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x40e7c01 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x40f4001 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x4215c01 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x4247c01 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x424fc01 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x4280403 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x4281402 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x4283004 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x428e003 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x428fc01 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x4294009 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x429fc01 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x42ce407 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x4400003 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x440e016 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x4420003 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x442c012 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x4440003 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x4449c0e as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x4450004 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x4460003 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x446cc0e as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x4471404 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x45aac0d as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x491c004 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x5bd442e as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x5be3c04 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x74000f6 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x7440027 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x744a4b5 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x7480046 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x74c0057 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x75b0401 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x75b6c01 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x75bec01 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x75c5401 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x75cd401 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x75d3c01 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x75dbc01 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x75e2401 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x75ea401 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x75f0c01 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x7bbc002 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x7c0002c as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x7c0c064 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x7c2800f as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x7c2c40e as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x7c3040f as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x7c3440f as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x7c4401f as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x7c4c03c as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x7c5c02b as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x7c7981d as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x7c8402b as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x7c90009 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x7c94002 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x7cc0021 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x7ccc006 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x7ccdc46 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x7ce0014 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x7ce8025 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x7cf1805 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x7cf8011 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x7d0003f as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x7d10001 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x7d108b6 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x7d3e404 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x7d4003e as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x7d50004 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x7d54018 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x7d7ec46 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x7d9140b as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x7da0046 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x7dc0074 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x38000401 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x38008060 as ::core::ffi::c_int as ::core::ffi::c_uint,
        0x380400f0 as ::core::ffi::c_int as ::core::ffi::c_uint,
    ];
    static mut aAscii: [::core::ffi::c_uint; 4] = [
        0xffffffff as ::core::ffi::c_uint,
        0xfc00ffff as ::core::ffi::c_uint,
        0xf8000001 as ::core::ffi::c_uint,
        0xf8000001 as ::core::ffi::c_uint,
    ];
    if (c as ::core::ffi::c_uint) < 128 as ::core::ffi::c_uint {
        return (aAscii[(c >> 5 as ::core::ffi::c_int) as usize]
            & (1 as ::core::ffi::c_int as ::core::ffi::c_uint) << (c & 0x1f as ::core::ffi::c_int)
            == 0 as ::core::ffi::c_uint) as ::core::ffi::c_int;
    } else if (c as ::core::ffi::c_uint)
        < ((1 as ::core::ffi::c_int) << 22 as ::core::ffi::c_int) as ::core::ffi::c_uint
    {
        let mut key: ::core::ffi::c_uint =
            (c as ::core::ffi::c_uint) << 10 as ::core::ffi::c_int | 0x3ff as ::core::ffi::c_uint;
        let mut iRes: ::core::ffi::c_int = 0 as ::core::ffi::c_int;
        let mut iHi: ::core::ffi::c_int =
            (::core::mem::size_of::<[::core::ffi::c_uint; 406]>() as usize)
                .wrapping_div(::core::mem::size_of::<::core::ffi::c_uint>() as usize)
                .wrapping_sub(1 as usize) as ::core::ffi::c_int;
        let mut iLo: ::core::ffi::c_int = 0 as ::core::ffi::c_int;
        while iHi >= iLo {
            let mut iTest: ::core::ffi::c_int = (iHi + iLo) / 2 as ::core::ffi::c_int;
            if key >= aEntry[iTest as usize] {
                iRes = iTest;
                iLo = iTest + 1 as ::core::ffi::c_int;
            } else {
                iHi = iTest - 1 as ::core::ffi::c_int;
            }
        }
        return (c as ::core::ffi::c_uint
            >= (aEntry[iRes as usize] >> 10 as ::core::ffi::c_int)
                .wrapping_add(aEntry[iRes as usize] & 0x3ff as ::core::ffi::c_uint))
            as ::core::ffi::c_int;
    }
    1 as ::core::ffi::c_int
}

unsafe extern "C" fn remove_diacritic(
    mut c: ::core::ffi::c_int,
    mut bComplex: ::core::ffi::c_int,
) -> ::core::ffi::c_int {
    let mut aDia: [::core::ffi::c_ushort; 126] = [
        0 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        1797 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        1848 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        1859 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        1891 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        1928 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        1940 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        1995 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        2024 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        2040 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        2060 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        2110 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        2168 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        2206 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        2264 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        2286 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        2344 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        2383 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        2472 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        2488 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        2516 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        2596 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        2668 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        2732 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        2782 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        2842 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        2894 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        2954 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        2984 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        3000 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        3028 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        3336 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        3456 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        3696 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        3712 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        3728 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        3744 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        3766 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        3832 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        3896 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        3912 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        3928 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        3944 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        3968 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        4008 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        4040 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        4056 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        4106 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        4138 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        4170 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        4202 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        4234 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        4266 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        4296 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        4312 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        4344 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        4408 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        4424 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        4442 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        4472 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        4488 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        4504 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        6148 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        6198 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        6264 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        6280 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        6360 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        6429 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        6505 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        6529 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        61448 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        61468 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        61512 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        61534 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        61592 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        61610 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        61642 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        61672 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        61688 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        61704 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        61726 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        61784 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        61800 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        61816 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        61836 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        61880 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        61896 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        61914 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        61948 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        61998 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        62062 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        62122 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        62154 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        62184 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        62200 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        62218 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        62252 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        62302 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        62364 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        62410 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        62442 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        62478 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        62536 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        62554 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        62584 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        62604 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        62640 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        62648 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        62656 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        62664 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        62730 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        62766 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        62830 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        62890 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        62924 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        62974 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        63032 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        63050 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        63082 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        63118 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        63182 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        63242 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        63274 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        63310 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        63368 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        63390 as ::core::ffi::c_int as ::core::ffi::c_ushort,
    ];
    let mut aChar: [::core::ffi::c_uchar; 126] = [
        '\0' as i32 as ::core::ffi::c_uchar,
        'a' as i32 as ::core::ffi::c_uchar,
        'c' as i32 as ::core::ffi::c_uchar,
        'e' as i32 as ::core::ffi::c_uchar,
        'i' as i32 as ::core::ffi::c_uchar,
        'n' as i32 as ::core::ffi::c_uchar,
        'o' as i32 as ::core::ffi::c_uchar,
        'u' as i32 as ::core::ffi::c_uchar,
        'y' as i32 as ::core::ffi::c_uchar,
        'y' as i32 as ::core::ffi::c_uchar,
        'a' as i32 as ::core::ffi::c_uchar,
        'c' as i32 as ::core::ffi::c_uchar,
        'd' as i32 as ::core::ffi::c_uchar,
        'e' as i32 as ::core::ffi::c_uchar,
        'e' as i32 as ::core::ffi::c_uchar,
        'g' as i32 as ::core::ffi::c_uchar,
        'h' as i32 as ::core::ffi::c_uchar,
        'i' as i32 as ::core::ffi::c_uchar,
        'j' as i32 as ::core::ffi::c_uchar,
        'k' as i32 as ::core::ffi::c_uchar,
        'l' as i32 as ::core::ffi::c_uchar,
        'n' as i32 as ::core::ffi::c_uchar,
        'o' as i32 as ::core::ffi::c_uchar,
        'r' as i32 as ::core::ffi::c_uchar,
        's' as i32 as ::core::ffi::c_uchar,
        't' as i32 as ::core::ffi::c_uchar,
        'u' as i32 as ::core::ffi::c_uchar,
        'u' as i32 as ::core::ffi::c_uchar,
        'w' as i32 as ::core::ffi::c_uchar,
        'y' as i32 as ::core::ffi::c_uchar,
        'z' as i32 as ::core::ffi::c_uchar,
        'o' as i32 as ::core::ffi::c_uchar,
        'u' as i32 as ::core::ffi::c_uchar,
        'a' as i32 as ::core::ffi::c_uchar,
        'i' as i32 as ::core::ffi::c_uchar,
        'o' as i32 as ::core::ffi::c_uchar,
        'u' as i32 as ::core::ffi::c_uchar,
        ('u' as i32 | HIBIT as ::core::ffi::c_int) as ::core::ffi::c_uchar,
        ('a' as i32 | HIBIT as ::core::ffi::c_int) as ::core::ffi::c_uchar,
        'g' as i32 as ::core::ffi::c_uchar,
        'k' as i32 as ::core::ffi::c_uchar,
        'o' as i32 as ::core::ffi::c_uchar,
        ('o' as i32 | HIBIT as ::core::ffi::c_int) as ::core::ffi::c_uchar,
        'j' as i32 as ::core::ffi::c_uchar,
        'g' as i32 as ::core::ffi::c_uchar,
        'n' as i32 as ::core::ffi::c_uchar,
        ('a' as i32 | HIBIT as ::core::ffi::c_int) as ::core::ffi::c_uchar,
        'a' as i32 as ::core::ffi::c_uchar,
        'e' as i32 as ::core::ffi::c_uchar,
        'i' as i32 as ::core::ffi::c_uchar,
        'o' as i32 as ::core::ffi::c_uchar,
        'r' as i32 as ::core::ffi::c_uchar,
        'u' as i32 as ::core::ffi::c_uchar,
        's' as i32 as ::core::ffi::c_uchar,
        't' as i32 as ::core::ffi::c_uchar,
        'h' as i32 as ::core::ffi::c_uchar,
        'a' as i32 as ::core::ffi::c_uchar,
        'e' as i32 as ::core::ffi::c_uchar,
        ('o' as i32 | HIBIT as ::core::ffi::c_int) as ::core::ffi::c_uchar,
        'o' as i32 as ::core::ffi::c_uchar,
        ('o' as i32 | HIBIT as ::core::ffi::c_int) as ::core::ffi::c_uchar,
        'y' as i32 as ::core::ffi::c_uchar,
        '\0' as i32 as ::core::ffi::c_uchar,
        '\0' as i32 as ::core::ffi::c_uchar,
        '\0' as i32 as ::core::ffi::c_uchar,
        '\0' as i32 as ::core::ffi::c_uchar,
        '\0' as i32 as ::core::ffi::c_uchar,
        '\0' as i32 as ::core::ffi::c_uchar,
        '\0' as i32 as ::core::ffi::c_uchar,
        '\0' as i32 as ::core::ffi::c_uchar,
        'a' as i32 as ::core::ffi::c_uchar,
        'b' as i32 as ::core::ffi::c_uchar,
        ('c' as i32 | HIBIT as ::core::ffi::c_int) as ::core::ffi::c_uchar,
        'd' as i32 as ::core::ffi::c_uchar,
        'd' as i32 as ::core::ffi::c_uchar,
        ('e' as i32 | HIBIT as ::core::ffi::c_int) as ::core::ffi::c_uchar,
        'e' as i32 as ::core::ffi::c_uchar,
        ('e' as i32 | HIBIT as ::core::ffi::c_int) as ::core::ffi::c_uchar,
        'f' as i32 as ::core::ffi::c_uchar,
        'g' as i32 as ::core::ffi::c_uchar,
        'h' as i32 as ::core::ffi::c_uchar,
        'h' as i32 as ::core::ffi::c_uchar,
        'i' as i32 as ::core::ffi::c_uchar,
        ('i' as i32 | HIBIT as ::core::ffi::c_int) as ::core::ffi::c_uchar,
        'k' as i32 as ::core::ffi::c_uchar,
        'l' as i32 as ::core::ffi::c_uchar,
        ('l' as i32 | HIBIT as ::core::ffi::c_int) as ::core::ffi::c_uchar,
        'l' as i32 as ::core::ffi::c_uchar,
        'm' as i32 as ::core::ffi::c_uchar,
        'n' as i32 as ::core::ffi::c_uchar,
        ('o' as i32 | HIBIT as ::core::ffi::c_int) as ::core::ffi::c_uchar,
        'p' as i32 as ::core::ffi::c_uchar,
        'r' as i32 as ::core::ffi::c_uchar,
        ('r' as i32 | HIBIT as ::core::ffi::c_int) as ::core::ffi::c_uchar,
        'r' as i32 as ::core::ffi::c_uchar,
        's' as i32 as ::core::ffi::c_uchar,
        ('s' as i32 | HIBIT as ::core::ffi::c_int) as ::core::ffi::c_uchar,
        't' as i32 as ::core::ffi::c_uchar,
        'u' as i32 as ::core::ffi::c_uchar,
        ('u' as i32 | HIBIT as ::core::ffi::c_int) as ::core::ffi::c_uchar,
        'v' as i32 as ::core::ffi::c_uchar,
        'w' as i32 as ::core::ffi::c_uchar,
        'w' as i32 as ::core::ffi::c_uchar,
        'x' as i32 as ::core::ffi::c_uchar,
        'y' as i32 as ::core::ffi::c_uchar,
        'z' as i32 as ::core::ffi::c_uchar,
        'h' as i32 as ::core::ffi::c_uchar,
        't' as i32 as ::core::ffi::c_uchar,
        'w' as i32 as ::core::ffi::c_uchar,
        'y' as i32 as ::core::ffi::c_uchar,
        'a' as i32 as ::core::ffi::c_uchar,
        ('a' as i32 | HIBIT as ::core::ffi::c_int) as ::core::ffi::c_uchar,
        ('a' as i32 | HIBIT as ::core::ffi::c_int) as ::core::ffi::c_uchar,
        ('a' as i32 | HIBIT as ::core::ffi::c_int) as ::core::ffi::c_uchar,
        'e' as i32 as ::core::ffi::c_uchar,
        ('e' as i32 | HIBIT as ::core::ffi::c_int) as ::core::ffi::c_uchar,
        ('e' as i32 | HIBIT as ::core::ffi::c_int) as ::core::ffi::c_uchar,
        'i' as i32 as ::core::ffi::c_uchar,
        'o' as i32 as ::core::ffi::c_uchar,
        ('o' as i32 | HIBIT as ::core::ffi::c_int) as ::core::ffi::c_uchar,
        ('o' as i32 | HIBIT as ::core::ffi::c_int) as ::core::ffi::c_uchar,
        ('o' as i32 | HIBIT as ::core::ffi::c_int) as ::core::ffi::c_uchar,
        'u' as i32 as ::core::ffi::c_uchar,
        ('u' as i32 | HIBIT as ::core::ffi::c_int) as ::core::ffi::c_uchar,
        ('u' as i32 | HIBIT as ::core::ffi::c_int) as ::core::ffi::c_uchar,
        'y' as i32 as ::core::ffi::c_uchar,
    ];
    let mut key: ::core::ffi::c_uint =
        (c as ::core::ffi::c_uint) << 3 as ::core::ffi::c_int | 0x7 as ::core::ffi::c_uint;
    let mut iRes: ::core::ffi::c_int = 0 as ::core::ffi::c_int;
    let mut iHi: ::core::ffi::c_int = (::core::mem::size_of::<[::core::ffi::c_ushort; 126]>()
        as usize)
        .wrapping_div(::core::mem::size_of::<::core::ffi::c_ushort>() as usize)
        .wrapping_sub(1 as usize) as ::core::ffi::c_int;
    let mut iLo: ::core::ffi::c_int = 0 as ::core::ffi::c_int;
    while iHi >= iLo {
        let mut iTest: ::core::ffi::c_int = (iHi + iLo) / 2 as ::core::ffi::c_int;
        if key >= aDia[iTest as usize] as ::core::ffi::c_uint {
            iRes = iTest;
            iLo = iTest + 1 as ::core::ffi::c_int;
        } else {
            iHi = iTest - 1 as ::core::ffi::c_int;
        }
    }
    if bComplex == 0 as ::core::ffi::c_int
        && aChar[iRes as usize] as ::core::ffi::c_int & 0x80 as ::core::ffi::c_int != 0
    {
        return c;
    }
    if c > (aDia[iRes as usize] as ::core::ffi::c_int >> 3 as ::core::ffi::c_int)
        + (aDia[iRes as usize] as ::core::ffi::c_int & 0x7 as ::core::ffi::c_int)
    {
        c
    } else {
        aChar[iRes as usize] as ::core::ffi::c_int & 0x7f as ::core::ffi::c_int
    }
}

pub const HIBIT: ::core::ffi::c_uchar = 0x80 as ::core::ffi::c_int as ::core::ffi::c_uchar;

#[cfg_attr(feature = "test", unsafe(no_mangle))]
pub unsafe extern "C" fn sqlite3FtsUnicodeIsdiacritic(
    mut c: ::core::ffi::c_int,
) -> ::core::ffi::c_int {
    let mut mask0: ::core::ffi::c_uint = 0x8029fdf as ::core::ffi::c_int as ::core::ffi::c_uint;
    let mut mask1: ::core::ffi::c_uint = 0x361f8 as ::core::ffi::c_int as ::core::ffi::c_uint;
    if c < 768 as ::core::ffi::c_int || c > 817 as ::core::ffi::c_int {
        return 0 as ::core::ffi::c_int;
    }
    (if c < 768 as ::core::ffi::c_int + 32 as ::core::ffi::c_int {
        mask0 & (1 as ::core::ffi::c_int as ::core::ffi::c_uint) << c - 768 as ::core::ffi::c_int
    } else {
        mask1
            & (1 as ::core::ffi::c_int as ::core::ffi::c_uint)
                << c - 768 as ::core::ffi::c_int - 32 as ::core::ffi::c_int
    }) as ::core::ffi::c_int
}

#[cfg_attr(feature = "test", unsafe(no_mangle))]
pub unsafe extern "C" fn sqlite3FtsUnicodeFold(
    mut c: ::core::ffi::c_int,
    mut eRemoveDiacritic: ::core::ffi::c_int,
) -> ::core::ffi::c_int {
    static mut aEntry: [TableEntry; 163] = [
        TableEntry {
            iCode: 65 as ::core::ffi::c_ushort,
            flags: 14 as ::core::ffi::c_uchar,
            nRange: 26 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 181 as ::core::ffi::c_ushort,
            flags: 64 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 192 as ::core::ffi::c_ushort,
            flags: 14 as ::core::ffi::c_uchar,
            nRange: 23 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 216 as ::core::ffi::c_ushort,
            flags: 14 as ::core::ffi::c_uchar,
            nRange: 7 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 256 as ::core::ffi::c_ushort,
            flags: 1 as ::core::ffi::c_uchar,
            nRange: 48 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 306 as ::core::ffi::c_ushort,
            flags: 1 as ::core::ffi::c_uchar,
            nRange: 6 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 313 as ::core::ffi::c_ushort,
            flags: 1 as ::core::ffi::c_uchar,
            nRange: 16 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 330 as ::core::ffi::c_ushort,
            flags: 1 as ::core::ffi::c_uchar,
            nRange: 46 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 376 as ::core::ffi::c_ushort,
            flags: 116 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 377 as ::core::ffi::c_ushort,
            flags: 1 as ::core::ffi::c_uchar,
            nRange: 6 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 383 as ::core::ffi::c_ushort,
            flags: 104 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 385 as ::core::ffi::c_ushort,
            flags: 50 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 386 as ::core::ffi::c_ushort,
            flags: 1 as ::core::ffi::c_uchar,
            nRange: 4 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 390 as ::core::ffi::c_ushort,
            flags: 44 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 391 as ::core::ffi::c_ushort,
            flags: 0 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 393 as ::core::ffi::c_ushort,
            flags: 42 as ::core::ffi::c_uchar,
            nRange: 2 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 395 as ::core::ffi::c_ushort,
            flags: 0 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 398 as ::core::ffi::c_ushort,
            flags: 32 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 399 as ::core::ffi::c_ushort,
            flags: 38 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 400 as ::core::ffi::c_ushort,
            flags: 40 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 401 as ::core::ffi::c_ushort,
            flags: 0 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 403 as ::core::ffi::c_ushort,
            flags: 42 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 404 as ::core::ffi::c_ushort,
            flags: 46 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 406 as ::core::ffi::c_ushort,
            flags: 52 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 407 as ::core::ffi::c_ushort,
            flags: 48 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 408 as ::core::ffi::c_ushort,
            flags: 0 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 412 as ::core::ffi::c_ushort,
            flags: 52 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 413 as ::core::ffi::c_ushort,
            flags: 54 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 415 as ::core::ffi::c_ushort,
            flags: 56 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 416 as ::core::ffi::c_ushort,
            flags: 1 as ::core::ffi::c_uchar,
            nRange: 6 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 422 as ::core::ffi::c_ushort,
            flags: 60 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 423 as ::core::ffi::c_ushort,
            flags: 0 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 425 as ::core::ffi::c_ushort,
            flags: 60 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 428 as ::core::ffi::c_ushort,
            flags: 0 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 430 as ::core::ffi::c_ushort,
            flags: 60 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 431 as ::core::ffi::c_ushort,
            flags: 0 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 433 as ::core::ffi::c_ushort,
            flags: 58 as ::core::ffi::c_uchar,
            nRange: 2 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 435 as ::core::ffi::c_ushort,
            flags: 1 as ::core::ffi::c_uchar,
            nRange: 4 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 439 as ::core::ffi::c_ushort,
            flags: 62 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 440 as ::core::ffi::c_ushort,
            flags: 0 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 444 as ::core::ffi::c_ushort,
            flags: 0 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 452 as ::core::ffi::c_ushort,
            flags: 2 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 453 as ::core::ffi::c_ushort,
            flags: 0 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 455 as ::core::ffi::c_ushort,
            flags: 2 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 456 as ::core::ffi::c_ushort,
            flags: 0 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 458 as ::core::ffi::c_ushort,
            flags: 2 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 459 as ::core::ffi::c_ushort,
            flags: 1 as ::core::ffi::c_uchar,
            nRange: 18 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 478 as ::core::ffi::c_ushort,
            flags: 1 as ::core::ffi::c_uchar,
            nRange: 18 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 497 as ::core::ffi::c_ushort,
            flags: 2 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 498 as ::core::ffi::c_ushort,
            flags: 1 as ::core::ffi::c_uchar,
            nRange: 4 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 502 as ::core::ffi::c_ushort,
            flags: 122 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 503 as ::core::ffi::c_ushort,
            flags: 134 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 504 as ::core::ffi::c_ushort,
            flags: 1 as ::core::ffi::c_uchar,
            nRange: 40 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 544 as ::core::ffi::c_ushort,
            flags: 110 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 546 as ::core::ffi::c_ushort,
            flags: 1 as ::core::ffi::c_uchar,
            nRange: 18 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 570 as ::core::ffi::c_ushort,
            flags: 70 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 571 as ::core::ffi::c_ushort,
            flags: 0 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 573 as ::core::ffi::c_ushort,
            flags: 108 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 574 as ::core::ffi::c_ushort,
            flags: 68 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 577 as ::core::ffi::c_ushort,
            flags: 0 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 579 as ::core::ffi::c_ushort,
            flags: 106 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 580 as ::core::ffi::c_ushort,
            flags: 28 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 581 as ::core::ffi::c_ushort,
            flags: 30 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 582 as ::core::ffi::c_ushort,
            flags: 1 as ::core::ffi::c_uchar,
            nRange: 10 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 837 as ::core::ffi::c_ushort,
            flags: 36 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 880 as ::core::ffi::c_ushort,
            flags: 1 as ::core::ffi::c_uchar,
            nRange: 4 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 886 as ::core::ffi::c_ushort,
            flags: 0 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 902 as ::core::ffi::c_ushort,
            flags: 18 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 904 as ::core::ffi::c_ushort,
            flags: 16 as ::core::ffi::c_uchar,
            nRange: 3 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 908 as ::core::ffi::c_ushort,
            flags: 26 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 910 as ::core::ffi::c_ushort,
            flags: 24 as ::core::ffi::c_uchar,
            nRange: 2 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 913 as ::core::ffi::c_ushort,
            flags: 14 as ::core::ffi::c_uchar,
            nRange: 17 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 931 as ::core::ffi::c_ushort,
            flags: 14 as ::core::ffi::c_uchar,
            nRange: 9 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 962 as ::core::ffi::c_ushort,
            flags: 0 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 975 as ::core::ffi::c_ushort,
            flags: 4 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 976 as ::core::ffi::c_ushort,
            flags: 140 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 977 as ::core::ffi::c_ushort,
            flags: 142 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 981 as ::core::ffi::c_ushort,
            flags: 146 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 982 as ::core::ffi::c_ushort,
            flags: 144 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 984 as ::core::ffi::c_ushort,
            flags: 1 as ::core::ffi::c_uchar,
            nRange: 24 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 1008 as ::core::ffi::c_ushort,
            flags: 136 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 1009 as ::core::ffi::c_ushort,
            flags: 138 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 1012 as ::core::ffi::c_ushort,
            flags: 130 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 1013 as ::core::ffi::c_ushort,
            flags: 128 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 1015 as ::core::ffi::c_ushort,
            flags: 0 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 1017 as ::core::ffi::c_ushort,
            flags: 152 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 1018 as ::core::ffi::c_ushort,
            flags: 0 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 1021 as ::core::ffi::c_ushort,
            flags: 110 as ::core::ffi::c_uchar,
            nRange: 3 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 1024 as ::core::ffi::c_ushort,
            flags: 34 as ::core::ffi::c_uchar,
            nRange: 16 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 1040 as ::core::ffi::c_ushort,
            flags: 14 as ::core::ffi::c_uchar,
            nRange: 32 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 1120 as ::core::ffi::c_ushort,
            flags: 1 as ::core::ffi::c_uchar,
            nRange: 34 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 1162 as ::core::ffi::c_ushort,
            flags: 1 as ::core::ffi::c_uchar,
            nRange: 54 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 1216 as ::core::ffi::c_ushort,
            flags: 6 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 1217 as ::core::ffi::c_ushort,
            flags: 1 as ::core::ffi::c_uchar,
            nRange: 14 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 1232 as ::core::ffi::c_ushort,
            flags: 1 as ::core::ffi::c_uchar,
            nRange: 88 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 1329 as ::core::ffi::c_ushort,
            flags: 22 as ::core::ffi::c_uchar,
            nRange: 38 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 4256 as ::core::ffi::c_ushort,
            flags: 66 as ::core::ffi::c_uchar,
            nRange: 38 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 4295 as ::core::ffi::c_ushort,
            flags: 66 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 4301 as ::core::ffi::c_ushort,
            flags: 66 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 7680 as ::core::ffi::c_ushort,
            flags: 1 as ::core::ffi::c_uchar,
            nRange: 150 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 7835 as ::core::ffi::c_ushort,
            flags: 132 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 7838 as ::core::ffi::c_ushort,
            flags: 96 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 7840 as ::core::ffi::c_ushort,
            flags: 1 as ::core::ffi::c_uchar,
            nRange: 96 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 7944 as ::core::ffi::c_ushort,
            flags: 150 as ::core::ffi::c_uchar,
            nRange: 8 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 7960 as ::core::ffi::c_ushort,
            flags: 150 as ::core::ffi::c_uchar,
            nRange: 6 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 7976 as ::core::ffi::c_ushort,
            flags: 150 as ::core::ffi::c_uchar,
            nRange: 8 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 7992 as ::core::ffi::c_ushort,
            flags: 150 as ::core::ffi::c_uchar,
            nRange: 8 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 8008 as ::core::ffi::c_ushort,
            flags: 150 as ::core::ffi::c_uchar,
            nRange: 6 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 8025 as ::core::ffi::c_ushort,
            flags: 151 as ::core::ffi::c_uchar,
            nRange: 8 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 8040 as ::core::ffi::c_ushort,
            flags: 150 as ::core::ffi::c_uchar,
            nRange: 8 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 8072 as ::core::ffi::c_ushort,
            flags: 150 as ::core::ffi::c_uchar,
            nRange: 8 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 8088 as ::core::ffi::c_ushort,
            flags: 150 as ::core::ffi::c_uchar,
            nRange: 8 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 8104 as ::core::ffi::c_ushort,
            flags: 150 as ::core::ffi::c_uchar,
            nRange: 8 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 8120 as ::core::ffi::c_ushort,
            flags: 150 as ::core::ffi::c_uchar,
            nRange: 2 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 8122 as ::core::ffi::c_ushort,
            flags: 126 as ::core::ffi::c_uchar,
            nRange: 2 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 8124 as ::core::ffi::c_ushort,
            flags: 148 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 8126 as ::core::ffi::c_ushort,
            flags: 100 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 8136 as ::core::ffi::c_ushort,
            flags: 124 as ::core::ffi::c_uchar,
            nRange: 4 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 8140 as ::core::ffi::c_ushort,
            flags: 148 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 8152 as ::core::ffi::c_ushort,
            flags: 150 as ::core::ffi::c_uchar,
            nRange: 2 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 8154 as ::core::ffi::c_ushort,
            flags: 120 as ::core::ffi::c_uchar,
            nRange: 2 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 8168 as ::core::ffi::c_ushort,
            flags: 150 as ::core::ffi::c_uchar,
            nRange: 2 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 8170 as ::core::ffi::c_ushort,
            flags: 118 as ::core::ffi::c_uchar,
            nRange: 2 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 8172 as ::core::ffi::c_ushort,
            flags: 152 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 8184 as ::core::ffi::c_ushort,
            flags: 112 as ::core::ffi::c_uchar,
            nRange: 2 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 8186 as ::core::ffi::c_ushort,
            flags: 114 as ::core::ffi::c_uchar,
            nRange: 2 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 8188 as ::core::ffi::c_ushort,
            flags: 148 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 8486 as ::core::ffi::c_ushort,
            flags: 98 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 8490 as ::core::ffi::c_ushort,
            flags: 92 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 8491 as ::core::ffi::c_ushort,
            flags: 94 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 8498 as ::core::ffi::c_ushort,
            flags: 12 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 8544 as ::core::ffi::c_ushort,
            flags: 8 as ::core::ffi::c_uchar,
            nRange: 16 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 8579 as ::core::ffi::c_ushort,
            flags: 0 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 9398 as ::core::ffi::c_ushort,
            flags: 10 as ::core::ffi::c_uchar,
            nRange: 26 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 11264 as ::core::ffi::c_ushort,
            flags: 22 as ::core::ffi::c_uchar,
            nRange: 47 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 11360 as ::core::ffi::c_ushort,
            flags: 0 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 11362 as ::core::ffi::c_ushort,
            flags: 88 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 11363 as ::core::ffi::c_ushort,
            flags: 102 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 11364 as ::core::ffi::c_ushort,
            flags: 90 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 11367 as ::core::ffi::c_ushort,
            flags: 1 as ::core::ffi::c_uchar,
            nRange: 6 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 11373 as ::core::ffi::c_ushort,
            flags: 84 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 11374 as ::core::ffi::c_ushort,
            flags: 86 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 11375 as ::core::ffi::c_ushort,
            flags: 80 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 11376 as ::core::ffi::c_ushort,
            flags: 82 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 11378 as ::core::ffi::c_ushort,
            flags: 0 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 11381 as ::core::ffi::c_ushort,
            flags: 0 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 11390 as ::core::ffi::c_ushort,
            flags: 78 as ::core::ffi::c_uchar,
            nRange: 2 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 11392 as ::core::ffi::c_ushort,
            flags: 1 as ::core::ffi::c_uchar,
            nRange: 100 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 11499 as ::core::ffi::c_ushort,
            flags: 1 as ::core::ffi::c_uchar,
            nRange: 4 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 11506 as ::core::ffi::c_ushort,
            flags: 0 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 42560 as ::core::ffi::c_ushort,
            flags: 1 as ::core::ffi::c_uchar,
            nRange: 46 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 42624 as ::core::ffi::c_ushort,
            flags: 1 as ::core::ffi::c_uchar,
            nRange: 24 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 42786 as ::core::ffi::c_ushort,
            flags: 1 as ::core::ffi::c_uchar,
            nRange: 14 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 42802 as ::core::ffi::c_ushort,
            flags: 1 as ::core::ffi::c_uchar,
            nRange: 62 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 42873 as ::core::ffi::c_ushort,
            flags: 1 as ::core::ffi::c_uchar,
            nRange: 4 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 42877 as ::core::ffi::c_ushort,
            flags: 76 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 42878 as ::core::ffi::c_ushort,
            flags: 1 as ::core::ffi::c_uchar,
            nRange: 10 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 42891 as ::core::ffi::c_ushort,
            flags: 0 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 42893 as ::core::ffi::c_ushort,
            flags: 74 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 42896 as ::core::ffi::c_ushort,
            flags: 1 as ::core::ffi::c_uchar,
            nRange: 4 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 42912 as ::core::ffi::c_ushort,
            flags: 1 as ::core::ffi::c_uchar,
            nRange: 10 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 42922 as ::core::ffi::c_ushort,
            flags: 72 as ::core::ffi::c_uchar,
            nRange: 1 as ::core::ffi::c_uchar,
        },
        TableEntry {
            iCode: 65313 as ::core::ffi::c_ushort,
            flags: 14 as ::core::ffi::c_uchar,
            nRange: 26 as ::core::ffi::c_uchar,
        },
    ];
    static mut aiOff: [::core::ffi::c_ushort; 77] = [
        1 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        2 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        8 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        15 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        16 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        26 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        28 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        32 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        37 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        38 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        40 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        48 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        63 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        64 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        69 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        71 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        79 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        80 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        116 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        202 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        203 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        205 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        206 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        207 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        209 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        210 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        211 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        213 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        214 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        217 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        218 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        219 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        775 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        7264 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        10792 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        10795 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        23228 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        23256 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        30204 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        54721 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        54753 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        54754 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        54756 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        54787 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        54793 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        54809 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        57153 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        57274 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        57921 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        58019 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        58363 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        61722 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        65268 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        65341 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        65373 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        65406 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        65408 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        65410 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        65415 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        65424 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        65436 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        65439 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        65450 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        65462 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        65472 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        65476 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        65478 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        65480 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        65482 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        65488 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        65506 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        65511 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        65514 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        65521 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        65527 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        65528 as ::core::ffi::c_int as ::core::ffi::c_ushort,
        65529 as ::core::ffi::c_int as ::core::ffi::c_ushort,
    ];
    let mut ret: ::core::ffi::c_int = c;
    if c < 128 as ::core::ffi::c_int {
        if c >= 'A' as i32 && c <= 'Z' as i32 {
            ret = c + ('a' as i32 - 'A' as i32);
        }
    } else if c < 65536 as ::core::ffi::c_int {
        let mut p: *const TableEntry = ::core::ptr::null::<TableEntry>();
        let mut iHi: ::core::ffi::c_int = (::core::mem::size_of::<[TableEntry; 163]>() as usize)
            .wrapping_div(::core::mem::size_of::<TableEntry>() as usize)
            .wrapping_sub(1 as usize)
            as ::core::ffi::c_int;
        let mut iLo: ::core::ffi::c_int = 0 as ::core::ffi::c_int;
        let mut iRes: ::core::ffi::c_int = -(1 as ::core::ffi::c_int);
        while iHi >= iLo {
            let mut iTest: ::core::ffi::c_int = (iHi + iLo) / 2 as ::core::ffi::c_int;
            let mut cmp: ::core::ffi::c_int =
                c - aEntry[iTest as usize].iCode as ::core::ffi::c_int;
            if cmp >= 0 as ::core::ffi::c_int {
                iRes = iTest;
                iLo = iTest + 1 as ::core::ffi::c_int;
            } else {
                iHi = iTest - 1 as ::core::ffi::c_int;
            }
        }
        p = (&raw const aEntry as *const TableEntry).offset(iRes as isize) as *const TableEntry
            as *const TableEntry;
        if c < (*p).iCode as ::core::ffi::c_int + (*p).nRange as ::core::ffi::c_int
            && 0 as ::core::ffi::c_int
                == 0x1 as ::core::ffi::c_int
                    & (*p).flags as ::core::ffi::c_int
                    & ((*p).iCode as ::core::ffi::c_int ^ c)
        {
            ret = c + aiOff[((*p).flags as ::core::ffi::c_int >> 1 as ::core::ffi::c_int) as usize]
                as ::core::ffi::c_int
                & 0xffff as ::core::ffi::c_int;
        }
        if eRemoveDiacritic != 0 {
            ret = remove_diacritic(
                ret,
                (eRemoveDiacritic == 2 as ::core::ffi::c_int) as ::core::ffi::c_int,
            );
        }
    } else if c >= 66560 as ::core::ffi::c_int && c < 66600 as ::core::ffi::c_int {
        ret = c + 40 as ::core::ffi::c_int;
    }
    ret
}
